### ISSUE TITLE
missing deleted mod from kkmanager know as enimiroah twilek head mod cause conflict 

### ISSUE THREAD

**Issue by ctmbottomtext** [BetterRepack/SideloaderModpackTracker#17]
**Name of mod**
enimaroah twilek head

**Description of issue**
certain cards that used the old none mod of preset hair are bugged because the mod was deleted and replaced with a less broken one maybe a small patch can fix this problem so people can enjoy cards with this problem out

**To Reproduce**

cards that used that missing mod automatically activate long hair preset

**Screenshots**

![Captura de pantalla (2909)](https://github.com/BetterRepack/SideloaderModpackTracker/assets/109061333/4538a2e8-f7b7-4c3c-a14b-7532fe99ff31)
![Captura de pantalla (2908)](https://github.com/BetterRepack/SideloaderModpackTracker/assets/109061333/40a896a9-f1dc-4375-a275-e6d15ea6ed44)

**Comment by 0192nxossz** [comment]
I have a question. Where am I supposed to find the file that has the Enimiroah Twilek Head mod?

**Comment by ManlyMarco** [comment]
You can ask for it on the discord server but it's recommended to not use it since it's broken.

**Comment by 11037-ceylon** [comment]
> 你可以在 Discord 伺服器上詢問，但由於它已損壞，建議不要使用。

Hi! I have a card that used Enimaroah's Twilek Head mod. 
I know it’s broken, but I really love this character and don’t want to remake it. 
Is there any way to repair or replace the missing head without losing her face shape?
