### ISSUE TITLE
[AIS/HS2] - [Duplicate SENA / sena directory]

### ISSUE THREAD

**Issue by johanaxel007** [BetterRepack/SideloaderModpackTracker#2]
**Name of modpack**
AIS/HS2 - [Sideloader Modpack - Studio](https://sideload.betterrepack.com/download/AISHS2/Sideloader%20Modpack%20-%20Studio)

**Description of issue**
Their is a duplicate [SENA](https://sideload.betterrepack.com/download/AISHS2/Sideloader%20Modpack%20-%20Studio/SENA/) / [sena](https://sideload.betterrepack.com/download/AISHS2/Sideloader%20Modpack%20-%20Studio/sena/) directory with the same contents. This confuses the KKManager updater into re-downloading the following files, even though they already exist (see screenshots section).

**To Reproduce**
Run the KKManager updater on AIS / HS2 and try to update the Sideloader Modpack - Items for Studio section

**Screenshots**
KKManager
![image](https://user-images.githubusercontent.com/27920724/154843489-86d38289-9c23-4d11-b9e4-77501139a722.png)

Sideloader Modpack - Studio directory
![image](https://user-images.githubusercontent.com/27920724/154843804-5590ac26-5fab-42f1-aa25-c0ffd4c75050.png)

SENA directory
![image](https://user-images.githubusercontent.com/27920724/154843747-88882378-6655-42a3-ae27-9c74820ed042.png)

**Comment by ScrewThisNoise** [comment]
Resolved
