### ISSUE TITLE
8246asdf.UpperEyes - Missing GUIDMigration info?

### ISSUE THREAD

**Issue by Kokaiinum** [BetterRepack/SideloaderModpackTracker#3]
8246asdf.UpperEyes ([DEF] Upper Eyes v1.0.zipmod)

The version of this mod currently included in the modpack appears to be missing the GUID migration info it had previously. The migration info that it probably should have is below: 
```
<info migrationType="MigrateAll" guidOld="8246asdf.Eyelines" guidNew="8246asdf.UpperEyes" />
```

**Comment by DeathWeasel1337** [comment]
Fixed, thanks

**Comment by Trashfish468** [comment]
<info migrationType="MigrateAll" guidOld="8246asdf.Eyelines" guidNew="8246asdf.UpperEyes" />
