### ISSUE TITLE
KKS-clothing-ported mods shouldn't be included for KKS.

### ISSUE THREAD

**Issue by OmegaKK** [BetterRepack/SideloaderModpackTracker#5]
Hello, so there are some mods featuring KK Sunshine clothing for Koikatsu, because KKS is already have everything from the old game. The issue is that KK_Manager automatically download these mods for KKS as well. So my game have one vanilla clothing and another "vanilla" clothing from mods, my suggestion is to give a new option to KK_Manager, asking player if they wants to download KKS clothing mods to Koikatsu Sunshine or not, and also remember selection. Assuming the game already have mods, KK_Manager should ask player if they wants to remove KKS-clothing mods or not on first time detecting these mods.
It could save resource and make clothing lists shorter, less confusing.

**Comment by ScrewThisNoise** [comment]
It has been included for card porting compatibility. They can be hidden by the user if he doesn't wish to have them in his list.
