### ISSUE TITLE
[Omega] HS2-KK Pack v1.7.zipmod - Missing _low animators for right shoe of Concierge [high boots]

### ISSUE THREAD

**Issue by IDontHaveIdea** [BetterRepack/SideloaderModpackTracker#6]
**Name of mod**
[Omega] HS2-KK Pack v1.7.zipmod

**Description of issue**
Missing _low animators for right shoe of Concierge [high boots]

**To Reproduce**
1. Assign Concierge [high boots] to a character coordinate
2. Don't activate High Poly plugin
3. Play game.

**Screenshots**

![NoBoot](https://user-images.githubusercontent.com/88360628/166092447-03134afa-75ad-46ee-8cf6-ebc5e1a0b3e7.png)

**Comment by OmegaKK** [comment]
This is an easy fix, will be include in next update. Thank you for reporting!

**Comment by ScrewThisNoise** [comment]
Not a problem with the sideloader modpack. Omega has been informed, closing issue
