### ISSUE TITLE
[BN2] BN2soundmod - Appears to be broken

### ISSUE THREAD

**Issue by Kokaiinum** [BetterRepack/SideloaderModpackTracker#7]
"Sound mod" or "3DSE" (in the Discord release post)

The version of the mod in the modpack appears to be broken. Maybe one of the tools doesn't know how to handle this type of mod (sound effects)?

The sound effect items in the version in the modpack simply don't appear to work. The one from the latest post in the mod-sharing channel on the Discord does work, however.

**Comment by ScrewThisNoise** [comment]
Which mods exactly is this about?

**Comment by ScrewThisNoise** [comment]
Ah, found it [BN2] BN2soundmod v4.0.zipmod has been reuploaded
